<?php
echo "ENTER YOUR EMAIL ADRESS<br>";
echo "UNDER CONSTRUCTION: currently there's no form here to submit your email adress and have a link send to it in order to set a new password.";
//HIER MOET EEN HTML FORMULIER KOMEN DAT LINKT MET PHP CODE VOOR HET AUTOMATISCH VERSTUREN VAN EEN LINK VOOR HET AANMAKEN VAN EEN NIEUW WACHTWOORD (GELINKT NAAR EEN FORMULIER MET DUBBEL WACHTWOORD)
